name: Convert to pdf

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Convert with pandoc
        uses: docker://pandoc/latex:2.9
        with:
          args: >-
            --standalone
            --output=demo.pdf
            src/demo.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: uploaded_demo.pdf
          path: demo.pdf
